### PR TITLE
travis: add osx

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/prebuild/prebuild/issues/200

### CODE REVIEW

**Comment by ralphtheninja** [comment]
It's been over 2 hours now and the osx builds haven't started.

**Comment by juliangruber** [comment]
travis had a major outage last week, and are still struggling it seems: https://twitter.com/traviscistatus?lang=de.

I'd say we wait this out and pray for our good travis :)

**Comment by juliangruber** [comment]
see in particular regarding osx: https://www.traviscistatus.com/incidents/1p7kw5hl4n1g

**Comment by ungoldman** [comment]
Can confirm macOS builds are usually significantly slower to start even on good days 😢 

Hopefully they will resolve the issue and make more macOS machines available sometime soon.

**Comment by ralphtheninja** [comment]
> Hopefully they will resolve the issue and make more macOS machines available sometime soon.

Aye, especially since they are needed to create prebuilt binaries :wink:

**Pull request merged**
