### PR TITLE
fix travis badge + update node versions

### PR DESCRIPTION
**Pull request by ralphtheninja**
Resolves https://github.com/prebuild/prebuild/issues/188 https://github.com/prebuild/prebuild/issues/191

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Hmm fails on 0.12. Maybe we should remove support for 0.10 and 0.12 now.

**Comment by mathiask88** [comment]
Maybe we should release one last minor that fixes the dependencies to the level they were 0.x compatible and then go for a new major and drop 0.x?

**Comment by lgeiger** [comment]
:+1: for removing support for Node 0.10 and 0.12

**Comment by ralphtheninja** [comment]
@mathiask88 How would we do that? Revert `node-gyp` to an older version?

**Comment by mathiask88** [comment]
@ralphtheninja Yes I meant to fix the dependencies to the latest version they work with 0.x But I don't mind not doing it.

**Comment by ralphtheninja** [comment]
> @ralphtheninja Yes I meant to fix the dependencies to the latest version they work with 0.x But I don't mind not doing it.

Cool. I still think we should release a new major though when dropping 0.x support.

**Comment by ralphtheninja** [comment]
Will release a new major after this PR has been merged.

**Comment by ralphtheninja** [comment]
7.0.0

**Pull request merged**
