### PR TITLE
make distributed files regex configurable AND support multiple .node files

### PR DESCRIPTION
**Pull request by antoinepairet**
This PR is the same as #122 with conflicts resolved. It replaces #170 and solves #169 

Feedback welcome :-)

### CODE REVIEW

**Comment by antoinepairet** [comment]
Building LWIP works :-)
Uploading to GH does not work. Will debug ASAP

screen shot 2017-03-30 at 12 30 51

**Comment by ralphtheninja** [comment]
Forgot to check this one. @antoinepairet Mind rebasing it?

**Comment by ralphtheninja** [comment]
@todbot Might be related to different versions of `node-gyp`, but just guessing.

**Comment by daviwil** [comment]
Any chance of getting this finished up and merged soon?  I just started using prebuild for [node-pty-prebuilt](https://github.com/daviwil/node-pty-prebuilt) and really need this behavior for the Windows build :)  Thanks a bunch for putting together this PR!

**Comment by daviwil** [comment]
I'll see if I can finish this up and fix the issue @todbot saw.

**Comment by daviwil** [comment]
@todbot would it be enough to have a parameter that allows you to identify the main .node file?  Something like `prebuild-install --main-module main.node`?

**Comment by daviwil** [comment]
You'd change your install script here to include the parameter:

https://github.com/node-hid/node-hid/blob/master/package.json#L18

The problem is that the extraction process is storing the `binaryName` as [whatever the last `.node` file](https://github.com/prebuild/prebuild-install/blob/master/download.js#L108) that is seen, then [this line](https://github.com/prebuild/prebuild-install/blob/master/download.js#L135) imports that file.

Maybe the right parameter is `--binary-name` or `--main-binary-name` based on what I see in the code.

**Comment by daviwil** [comment]
Not a problem :)  I'll send out an updated PR for #171 and then I'll make the change to prebuild-install.

**Comment by ralphtheninja** [comment]
Superseded by https://github.com/prebuild/prebuild/pull/192 and released in `7.1.0`

**Pull request closed without merging**
