### PR TITLE
add node-webkit to short description + add keyword

### PR DESCRIPTION
**Pull request by ralphtheninja**
Some final tweaks before releasing 7.3.0

### CODE REVIEW

**Comment by ralphtheninja** [comment]
I just realized I'm on a new computer and don't have access to npm login details so can't publish 😀 

@juliangruber Hilfe! Mind releasing a new minor?

**Comment by ralphtheninja** [comment]
@juliangruber Nevermind, I got it sorted.

**Comment by ralphtheninja** [comment]
7.3.0

**Comment by juliangruber** [comment]
:metal:

**Pull request merged**
