### PR TITLE
downgrade nsp for node 4

### PR DESCRIPTION
**Pull request by ralphtheninja**
This is only devDependencies so no biggie. I tried to get a PR through to `nsp` to remove stupid destructuring issue, but it was rejected.

### CODE REVIEW

**Comment by juliangruber** [comment]
I'm +-0, `nsp` is a good dependency to have up to date, but I can see people being stuck on node 4 too

**Comment by juliangruber** [comment]
If I have to decide, my vote is for future instead of past

**Comment by ralphtheninja** [comment]
We have to live with that tests will not work on node 4 then.

**Comment by ungoldman** [comment]
Might be worth requesting nsp maintain compatibility with Node 4 bit longer.

**Comment by ralphtheninja** [comment]
> Might be worth requesting nsp maintain compatibility with Node 4 bit longer.

@ungoldman I have, but it was rejected.

**Comment by ralphtheninja** [comment]
It's cool though, this only means we can't run the tests on node 4, so no biggie.

**Comment by vweevers** [comment]
How about skipping the `nsp check` command on node 4?

**Comment by ralphtheninja** [comment]
@vweevers Wanna make a PR? :)

**Comment by vweevers** [comment]
#197

**Pull request closed without merging**
